apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: wikicode-test
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/LouisRichards/wikicode-app-config.git
    targetRevision: HEAD
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: wikicode-test

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true

