apiVersion: v1
kind: Service
metadata:
  name: wikicodetest
  annotations:
    service.beta.kubernetes.io/linode-loadbalancer-throttler: "4"
  labels:
    app: wikicodetest
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    app: wikicodetest
  sessionAffinity: None
